config/routes.rb
Rails.application.routes.draw do
  resources :routes

  get "custom" => "routes#custom"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "routes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/route.rb
class Route < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/routes_controller.rb
strava_access_token = ENV["STRAVA_ACCESS_TOKEN"]
StravaClient = Strava::Api::Client.new(access_token: strava_access_token)

class RoutesController < ApplicationController
  before_action :set_route, only: %i[ show edit update destroy ]

  def create_route(route)
    gpx = Base64.encode64(StravaClient.export_route_gpx(route["id"]))
    Route.create(name: route["name"], route_updated_at: route["updated_at"], route_id: route["id"], gpx: gpx)
  end

  def custom
    @routes = JSON.parse(File.read(Rails.root.join("archive", "strava-routes.json")))
    @routes.each do |route|
      if not Route.exists?(name: route["name"])
        create_route(route)
      end

      saved_route = Route.find_by(name: route["name"])
      current_route_updated_at = Time.parse(route["updated_at"]).iso8601


      if current_route_updated_at != saved_route.route_updated_at.iso8601
        saved_route.destroy
        saved_route = create_route(route)
        saved_route.update(process: true)
      end

      if saved_route.process # we do stuff in Garmin Connect or wherever

        # ... then we remove the process flag
        saved_route.update(process: false)
      end
    end
  end

  # GET /routes or /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1 or /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes or /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      unless @route.save
        puts @route.errors.full_messages
      end

      if @route.save
        format.html { redirect_to @route, notice: "Route was successfully created." }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1 or /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: "Route was successfully updated." }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1 or /routes/1.json
  def destroy
    @route.destroy!

    respond_to do |format|
      format.html { redirect_to routes_path, status: :see_other, notice: "Route was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def route_params
      params.require(:route).permit(:name, :route_updated_at, :route_id, :gpx, :process)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Strava To Garmin Routes Synchronizer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/routes/_form.html.erb
<%= form_with(model: route) do |form| %>
  <% if route.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
        <% route.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :route_id, style: "display: block" %>
    <%= form.number_field :route_id %>
  </div>

  <div>
    <%= form.label :route_updated_at, style: "display: block" %>
    <%= form.datetime_field :route_updated_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/_route.html.erb
<div id="<%= dom_id route %>">
  <p>
    <strong>Name:</strong>
    <%= route.name %>
  </p>
  <p>
    <strong>Updated on Strava:</strong>
    <%= route.route_updated_at %>
  </p>
</div>

app/views/routes/custom.html.erb
<h1>It works!</h1>

<div id="routes">
  <% @routes.each do |route| %>
    <p>Name: <%= route['name'] %></p>
  <% end %>
</div>

app/views/routes/edit.html.erb
<% content_for :title, "Editing route" %>

<h1>Editing route</h1>

<%= render "form", route: @route %>

<br>

<div>
  <%= link_to "Show this route", @route %> |
  <%= link_to "Back to routes", routes_path %>
</div>

app/views/routes/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Routes" %>
<h1>Routes</h1>

<%= button_to "Run Strava code", "custom", method: :get %>

<div id="routes">
  <% @routes.each do |route| %>
    <%= render route %>
    <p>
      <%= link_to "Show this route", route %>
    </p>
  <% end %>
</div>

<%= link_to "New route", new_route_path %>

app/views/routes/new.html.erb
<% content_for :title, "New route" %>

<h1>New route</h1>

<%= render "form", route: @route %>

<br>

<div>
  <%= link_to "Back to routes", routes_path %>
</div>

app/views/routes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @route %>

<div>
  <%= link_to "Edit this route", edit_route_path(@route) %> |
  <%= link_to "Back to routes", routes_path %>

  <%= button_to "Destroy this route", @route, method: :delete %>
</div>